EFE...........F...FEE.FEEEFF
======================================================================
ERROR: test_404 (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "app/tests.py", line 139, in test_404
    assert '<h1>Not found</h1>' in rv.data
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_album_table_redirect (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "app/tests.py", line 106, in test_album_table_redirect
    test_post_album()
NameError: name 'test_post_album' is not defined

======================================================================
ERROR: test_db17_concert_aa_relationship (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "app/tests.py", line 345, in test_db17_concert_aa_relationship
    Concert_AA_Association.aa_id == aa_result.id).filter(
AttributeError: 'NoneType' object has no attribute 'id'

======================================================================
ERROR: test_db18_delete_concert_aa_relationship (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "app/tests.py", line 365, in test_db18_delete_concert_aa_relationship
    Concert_AA_Association.aa_id == aa_result.id).filter(
AttributeError: 'NoneType' object has no attribute 'id'

======================================================================
ERROR: test_post_album (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "app/tests.py", line 87, in test_post_album
    assert 'Added' in rv.data
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_post_track (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "app/tests.py", line 117, in test_post_track
    assert 'Added' in rv.data
TypeError: a bytes-like object is required, not 'str'

======================================================================
ERROR: test_put_album (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "app/tests.py", line 95, in test_put_album
    test_post_album()
NameError: name 'test_post_album' is not defined

======================================================================
FAIL: test_about_redirect (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "app/tests.py", line 61, in test_about_redirect
    assert rv.status == '302 FOUND'
AssertionError

======================================================================
FAIL: test_db12_delete_track_artist_relationship (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "app/tests.py", line 238, in test_db12_delete_track_artist_relationship
    assert Track.query.filter_by(name='track_name').first() is None
AssertionError

======================================================================
FAIL: test_db16_delete_aa_relationship (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "app/tests.py", line 305, in test_db16_delete_aa_relationship
    assert (aa_result is not None)
AssertionError

======================================================================
FAIL: test_home_redirects (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "app/tests.py", line 48, in test_home_redirects
    assert rv.status == '302 FOUND'
AssertionError

======================================================================
FAIL: test_put_track (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "app/tests.py", line 132, in test_put_track
    assert rv.status == '200 SUCCESS'
AssertionError

======================================================================
FAIL: test_table_redirect (__main__.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "app/tests.py", line 67, in test_table_redirect
    assert rv.status == '302 FOUND'
AssertionError

----------------------------------------------------------------------
Ran 28 tests in 4.526s

FAILED (failures=6, errors=7)
Name            Stmts   Miss Branch BrPart  Cover   Missing
-----------------------------------------------------------
app/models.py     150      7      0      0    95%   71, 92, 121, 168, 219, 259, 298
app/tests.py      249     55      2      1    78%   62, 68-80, 89-91, 96-101, 107-109, 119-121, 133, 239, 307-313, 348-354, 368-390, 392->exit
-----------------------------------------------------------
TOTAL             399     62      2      1    84%
